# Generated by Django 5.1.4 on 2024-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 100 karakter girmelisin', max_length=100, verbose_name='Başlık')),
                ('content', models.TextField(unique=True, verbose_name='İçerik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi ?')),
                ('blog_population', models.CharField(blank=True, choices=[('kisisel_gelisim', 'Kişisel Gelişim'), ('ders', 'Ders')], max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
