# Generated by Django 5.1.4 on 2024-12-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_population',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated',
        ),
    ]
